services:
  api:
    build: .
    container_name: team_friends
    command: gunicorn --workers=3 --timeout=120 --worker-class=gevent --bind 0.0.0.0:8000 teamfriends.wsgi --reload
    volumes:
      - .:/code
    environment:
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "8000:8000"