services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - friends

  api:
    build: .
    container_name: api
    hostname: api
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - RABBITMQ_URL='amqp://guest:guest@rabbitmq:5672/'
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    networks:
      - friends

  celery-worker:
    build: .
    container_name: celery-worker
    hostname: celery-worker
    command: celery -A teamfriends worker -l info
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - RABBITMQ_URL='amqp://guest:guest@rabbitmq:5672/'
    depends_on:
      - rabbitmq
    networks:
      - friends

  celery-beat:
    build: .
    container_name: celery-beat
    hostname: celery-beat
    command: celery -A teamfriends beat -l info
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - RABBITMQ_URL='amqp://guest:guest@rabbitmq:5672/'
    depends_on:
      - rabbitmq
    networks:
      - friends

networks:
  friends:
    driver: bridge

volumes:
  rabbitmq_data:
