# Generated by Django 5.0.4 on 2024-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='receiver@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
